service: so-sure-v2

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${file(./.env.${opt:stage, self:provider.stage}.yml)}

functions:
  testHello:
    handler: tests/hello.handler
    events:
      - http: GET /tests/hello
  testLocalMysql:
    handler: tests/mysql-local.handler
    events:
      - http: GET /tests/mysql-local
  testLocalMongo:
    handler: tests/mongo-local.handler
    events:
      - http: GET /tests/mongo-local

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 3000
